name: playground
description: "A playground for fast implementations of tasks."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  
  flutter_native_splash: ^2.4.2
  flutter_launcher_icons: ^0.14.1
  dio: ^5.5.0+1
  image_picker: ^1.1.2
  logger: ^2.4.0
  shared_preferences: ^2.3.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  assets:
    - shorebird.yaml

  uses-material-design: true



  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
